steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'stub'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/tech-choices:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/tech-choices:latest'