steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "decrypt env"
    args:
      - kms
      - decrypt
      - --ciphertext-file=env.enc
      - --plaintext-file=.env
      - --location=global
      - --project=tech-choices
      - --keyring=build
      - --key=env
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/tech-choices:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        'tech-choices', 
        '--image', 
        'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA', 
        '--region', 
        'us-central1',
        '--allow-unauthenticated',
        '--platform',
        'gke' 
      ]
images:
  - 'gcr.io/$PROJECT_ID/tech-choices:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/tech-choices:latest'